exports.seed = function(knex, Promise) {
    // Deletes ALL existing entries
    return knex('doctors').del()
        .then(function() {
            // Inserts seed entries
            return knex('doctors').insert([
                { name: "James Smith", email: 'james@smith.com', bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", profile_picture: "https://hcplive.s3.amazonaws.com/v1_media/_image/happydoctor.jpg", password: "pass" },
                { name: "Jess Jones", email: 'jess@jones.com', bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", profile_picture: "https://mk0djressv4lkrqvp91s.kinstacdn.com/wp-content/uploads/2018/04/dr-jessica.png", password: "pass" },
                { name: "Meryl Krich", email: 'meryl@krich.com', bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", profile_picture: "https://www.pennstatehealth.org/psh-images/findaphysician/providers/smerrill1.jpg", password: "pass" }
            ]);
        });
};